# Generated by Django 4.1.5 on 2023-04-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='background_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(max_length=250, upload_to='static/background')),
            ],
        ),
        migrations.CreateModel(
            name='cold_coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold_coffee_image', models.ImageField(max_length=250, upload_to='static/background')),
                ('cold_text', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('caption', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='hot_coffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_coffee_image', models.ImageField(max_length=20, upload_to='static/background')),
                ('hot_text', models.CharField(max_length=250)),
                ('hot_price', models.IntegerField()),
                ('hot_caption', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='juice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jyuice_image', models.ImageField(max_length=20, upload_to='static/background')),
                ('jyuice_name', models.CharField(max_length=250)),
                ('jyuice_price', models.IntegerField()),
                ('jyuice_caption', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='special_iteams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_image', models.ImageField(max_length=250, upload_to='static/background')),
                ('special_text', models.CharField(max_length=250)),
                ('special_price', models.IntegerField()),
                ('special_caption', models.CharField(max_length=250)),
            ],
        ),
    ]
