# Generated by Django 4.1.5 on 2023-04-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='juicess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jyuice_image', models.ImageField(max_length=20, upload_to='static/background')),
                ('jyuice_name', models.CharField(max_length=250)),
                ('jyuice_price', models.IntegerField()),
                ('jyuice_caption', models.CharField(max_length=250)),
            ],
        ),
    ]
