# Generated by Django 4.1.5 on 2023-04-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_alter_juice_jyuice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hot_coffe',
            name='hot_coffee_image',
            field=models.ImageField(max_length=2000, upload_to='static/background'),
        ),
    ]
