# Generated by Django 4.1.5 on 2023-04-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_alter_hot_coffe_hot_coffee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='juicess',
        ),
    ]
